/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_stardustmodding_rs4j_docs_example_complex_MyOtherStruct */

#ifndef _Included_org_stardustmodding_rs4j_docs_example_complex_MyOtherStruct
#define _Included_org_stardustmodding_rs4j_docs_example_complex_MyOtherStruct
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_stardustmodding_rs4j_docs_example_complex_MyOtherStruct
 * Method:    jni_get_a
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_stardustmodding_rs4j_docs_example_complex_MyOtherStruct_jni_1get_1a
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_stardustmodding_rs4j_docs_example_complex_MyOtherStruct
 * Method:    jni_get_b
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_stardustmodding_rs4j_docs_example_complex_MyOtherStruct_jni_1get_1b
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_stardustmodding_rs4j_docs_example_complex_MyOtherStruct
 * Method:    jni_set_a
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_stardustmodding_rs4j_docs_example_complex_MyOtherStruct_jni_1set_1a
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_stardustmodding_rs4j_docs_example_complex_MyOtherStruct
 * Method:    jni_set_b
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_stardustmodding_rs4j_docs_example_complex_MyOtherStruct_jni_1set_1b
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_stardustmodding_rs4j_docs_example_complex_MyOtherStruct
 * Method:    jni_init_new
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_stardustmodding_rs4j_docs_example_complex_MyOtherStruct_jni_1init_1new
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
