<?xml  version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN"   "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0" >
<!-- Generated via Iro -->
<dict>
  <key>fileTypes</key>
  <array> 
    <string>rs4j</string>
   </array>
  <key>name</key>
  <string>rs4j</string>
  <key>patterns</key>
  <array> 
    <dict>
      <key>include</key>
      <string>#main</string>
    </dict>
   </array>
  <key>scopeName</key>
  <string>source.rs4j</string>
  <key>uuid</key>
  <string></string>
  <key>repository</key>
  <dict>
    <key>main</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>\b(fn|mut|optional|class|static|consumed)</string>
          <key>name</key>
          <string>keyword.rs4j</string>
        </dict>
        <dict>
          <key>match</key>
          <string>\b(String|str|bool|(i|u)(8|16|32|64)|f(32|64))</string>
          <key>name</key>
          <string>entity.name.type.rs4j</string>
        </dict>
        <dict>
          <key>match</key>
          <string>\b([a-z_\x{0024}][\w\x{0024}]*)</string>
          <key>name</key>
          <string>entity.name.rs4j</string>
        </dict>
        <dict>
          <key>match</key>
          <string>\b([A-Z][\w\$]*)</string>
          <key>name</key>
          <string>entity.name.type.rs4j</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#numeric</string>
        </dict>
        <dict>
          <key>begin</key>
          <string>(\{)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.rs4j</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#main__1</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\};)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.rs4j</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>\b([\x{003b}.\x{002c}\x{003a}\x{0026}-\x{003e}\x{003c}]+)</string>
          <key>name</key>
          <string>punctuation.rs4j</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(&amp;)</string>
          <key>name</key>
          <string>punctuation.rs4j</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(-&gt;)</string>
          <key>name</key>
          <string>punctuation.rs4j</string>
        </dict>
        <dict>
          <key>begin</key>
          <string>(\&quot;)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.rs4j</string>
            </dict>
          </dict>
          <key>contentName</key>
          <string>text.rs4j</string>
          <key>end</key>
          <string>(\&quot;)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.rs4j</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(\()</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.rs4j</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#main__3</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\))</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.rs4j</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>(//.*)</string>
          <key>name</key>
          <string>comment.rs4j</string>
        </dict>
        <dict>
          <key>match</key>
          <string>([^\s])</string>
          <key>name</key>
          <string>invalid.rs4j</string>
        </dict>
       </array>
    </dict>
    <key>main__1</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#main</string>
        </dict>
       </array>
    </dict>
    <key>main__2</key>
    <dict>
      <key>patterns</key>
      <array> 
       </array>
    </dict>
    <key>main__3</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#numeric</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(,)</string>
          <key>name</key>
          <string>punctuation.rs4j</string>
        </dict>
       </array>
    </dict>
    <key>numeric</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(\b\d+)</string>
          <key>name</key>
          <string>constant.numeric.rs4j</string>
        </dict>
       </array>
    </dict>
  </dict>
</dict>
</plist>
